### ISSUE TITLE
Error im LOG!

### ISSUE THREAD

**Issue by Wurzeldoktor** [Baumert7269/ioBroker.repetierserver#8]
Ich bekomme zwar die States im Gerätebaum, aber trotzdem immer wieder diese Ausgabe im Log....
Scheinbar irwo ein Fehler, ich kenne mich da aber zu wenig aus um mich auszukennen ^^
oder liegts dran, das ein Druck läuft während ich die Verbindung aufbauen wollte?
Danke
LG

host.tinkerboard | 2020-08-28 21:44:46.362 | info | Restart adapter system.adapter.repetierserver.0 because enabled
-- | -- | -- | --
host.tinkerboard | 2020-08-28 21:44:46.362 | info | instance system.adapter.repetierserver.0 terminated with code 0 (NO_ERROR)
repetierserver.0 | 2020-08-28 21:44:45.841 | info | (30458) Terminated (NO_ERROR): Without reason
repetierserver.0 | 2020-08-28 21:44:45.840 | info | (30458) terminating
repetierserver.0 | 2020-08-28 21:44:45.802 | info | (30458) Repetier-Server Service gestoppt...
repetierserver.0 | 2020-08-28 21:44:45.801 | info | (30458) Repetier-Server Verbindungsaufbau gestoppt...
repetierserver.0 | 2020-08-28 21:44:45.800 | info | (30458) Repetier-Server Service bereinigt...
**repetierserver.0 | 2020-08-28 21:44:45.798 | error | (30458) TypeError: Cannot read property 'val' of null     at /opt/iobroker/node_modules/iobroker.repetierserver/main.js:1003:63     at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/stat**
repetierserver.0 | 2020-08-28 21:44:45.796 | error | (30458) uncaught exception: Cannot read property 'val' of null
repetierserver.0 | 2020-08-28 21:44:45.290 | info | (30458) Druckteil #/AI3M_Anycubic_Bed_Leveling_wheel_3-pieces-1 wurde am Drucker >I3< gesetzt...
repetierserver.0 | 2020-08-28 21:44:43.233 | debug | (30458) RepetierServer states subscribed
repetierserver.0 | 2020-08-28 21:44:43.232 | info | (30458) Repetier Model-Management aktiv
repetierserver.0 | 2020-08-28 21:44:43.231 | info | (30458) Repetier Port: 3344
repetierserver.0 | 2020-08-28 21:44:43.231 | info | (30458) Repetier ApiKey: e5d64e87-xxxxxxxxxxxxxxxxxxxxx
repetierserver.0 | 2020-08-28 21:44:43.230 | info | (30458) Repetier IP: 192.168.0.151
repetierserver.0 | 2020-08-28 21:44:43.230 | info | (30458) RepetierServer verbunden
repetierserver.0 | 2020-08-28 21:44:43.200 | info | (30458) starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.repetierserver, node: v12.18.3, js-controller: 3.1.6
host.tinkerboard | 2020-08-28 21:44:41.644 | info | instance system.adapter.repetierserver.0 started with pid 30458
host.tinkerboard | 2020-08-28 21:44:11.618 | info | Restart adapter system.adapter.repetierserver.0 because enabled
host.tinkerboard | 2020-08-28 21:44:11.616 | info | instance system.adapter.repetierserver.0 terminated with code 0 (NO_ERROR)
repetierserver.0 | 2020-08-28 21:44:11.057 | info | (30381) Terminated (NO_ERROR): Without reason
repetierserver.0 | 2020-08-28 21:44:11.056 | info | (30381) terminating
repetierserver.0 | 2020-08-28 21:44:10.976 | info | (30381) Repetier-Server Service gestoppt...
repetierserver.0 | 2020-08-28 21:44:10.976 | info | (30381) Repetier-Server Verbindungsaufbau gestoppt...
repetierserver.0 | 2020-08-28 21:44:10.974 | info | (30381) Repetier-Server Service bereinigt...
**repetierserver.0 | 2020-08-28 21:44:10.973 | error | (30381) TypeError: Cannot read property 'val' of null     at /opt/iobroker/node_modules/iobroker.repetierserver/main.js:1003:63     at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/stat
repetierserver.0 | 2020-08-28 21:44:10.971 | error | (30381) uncaught exception: Cannot read property 'val' of null**
repetierserver.0 | 2020-08-28 21:44:10.462 | info | (30381) Druckteil #/AI3M_Anycubic_Bed_Leveling_wheel_3-pieces-1 wurde am Drucker >I3< gesetzt...
repetierserver.0 | 2020-08-28 21:44:08.408 | debug | (30381) RepetierServer states subscribed
repetierserver.0 | 2020-08-28 21:44:08.407 | info | (30381) Repetier Model-Management aktiv
repetierserver.0 | 2020-08-28 21:44:08.407 | info | (30381) Repetier Port: 3344
repetierserver.0 | 2020-08-28 21:44:08.406 | info | (30381) Repetier ApiKey: e5d64e87-xxx-xxxxxx-86c8-xxxxxxxxxxx
repetierserver.0 | 2020-08-28 21:44:08.406 | info | (30381) Repetier IP: 192.168.0.151
repetierserver.0 | 2020-08-28 21:44:08.405 | info | (30381) RepetierServer verbunden

**Comment by Bischof-Mak** [comment]
Hallo zusammen, habe leider das selbe Problem,

Er liefert Werte, der Adapter bricht aber immer wieder ab.
Habe die neueste Version genommen (0.0.3)
Bin gerne bereit, mehr WERTE zu liefern. Auch eine Fernwartung wäre denkbar :-)

Platform UBUNTU linux
Betriebssystem linux
Architektur x64
CPUs 2
Geschwindigkeit 1497 MHz
Modell Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM 3.84 GB
System Betriebszeit 1 T. 02:23:09
Node.js v12.20.1
NPM 6.14.10
Anzahl der Adapter 326
Festplatte Größe 23.99 GB
Festplatte frei 12.89 GB
Betriebszeit 1 T. 02:22:40
Aktive Instanzen 20

host.iobroker01 | 2021-02-10 20:10:30.048 | info | Restart adapter system.adapter.repetierserver.0 because enabled
-- | -- | -- | --
host.iobroker01 | 2021-02-10 20:10:30.046 | info | instance system.adapter.repetierserver.0 terminated with code 0 (NO_ERROR)
repetierserver.0 | 2021-02-10 20:10:29.505 | info | (17683) Terminated (NO_ERROR): Without reason
repetierserver.0 | 2021-02-10 20:10:29.504 | info | (17683) terminating
repetierserver.0 | 2021-02-10 20:10:29.321 | info | (17683) Repetier-Server Service gestoppt...
repetierserver.0 | 2021-02-10 20:10:29.320 | info | (17683) Repetier-Server Verbindungsaufbau gestoppt...
repetierserver.0 | 2021-02-10 20:10:29.319 | info | (17683) Repetier-Server Service bereinigt...
repetierserver.0 | 2021-02-10 20:10:29.318 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
repetierserver.0 | 2021-02-10 20:10:29.318 | error | at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
repetierserver.0 | 2021-02-10 20:10:29.318 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
repetierserver.0 | 2021-02-10 20:10:29.318 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:608:33
repetierserver.0 | 2021-02-10 20:10:29.318 | error | at /opt/iobroker/node_modules/iobroker.repetierserver/main.js:1003:63
repetierserver.0 | 2021-02-10 20:10:29.318 | error | (17683) TypeError: Cannot read property 'val' of null
repetierserver.0 | 2021-02-10 20:10:29.316 | error | (17683) uncaught exception: Cannot read property 'val' of null
repetierserver.0 | 2021-02-10 20:10:26.719 | debug | (17683) RepetierServer states subscribed
repetierserver.0 | 2021-02-10 20:10:26.716 | info | (17683) Repetier Port: 3344
repetierserver.0 | 2021-02-10 20:10:26.715 | info | (17683) Repetier ApiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repetierserver.0 | 2021-02-10 20:10:26.714 | info | (17683) Repetier IP: 192.168.200.52
repetierserver.0 | 2021-02-10 20:10:26.713 | info | (17683) RepetierServer verbunden
repetierserver.0 | 2021-02-10 20:10:26.672 | info | (17683) starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.repetierserver, node: v12.20.1, js-controller: 3.1.6
repetierserver.0 | 2021-02-10 20:10:25.643 | debug | (17683) statesDB connected
repetierserver.0 | 2021-02-10 20:10:25.642 | debug | (17683) States connected to redis: 127.0.0.1:9000
repetierserver.0 | 2021-02-10 20:10:25.630 | debug | (17683) States create System PubSub Client
repetierserver.0 | 2021-02-10 20:10:25.626 | debug | (17683) States create User PubSub Client
repetierserver.0 | 2021-02-10 20:10:25.618 | debug | (17683) Redis States: Use Redis connection: 127.0.0.1:9000
repetierserver.0 | 2021-02-10 20:10:25.616 | debug | (17683) objectDB connected
repetierserver.0 | 2021-02-10 20:10:25.609 | debug | (17683) Objects connected to redis: 127.0.0.1:9001
repetierserver.0 | 2021-02-10 20:10:25.594 | debug | (17683) Objects client initialize lua scripts
repetierserver.0 | 2021-02-10 20:10:25.577 | debug | (17683) Objects create User PubSub Client
repetierserver.0 | 2021-02-10 20:10:25.575 | debug | (17683) Objects create System PubSub Client
repetierserver.0 | 2021-02-10 20:10:25.570 | debug | (17683) Objects client ready ... initialize now
repetierserver.0 | 2021-02-10 20:10:25.514 | debug | (17683) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iobroker01 | 2021-02-10 20:10:24.236 | info | instance system.adapter.repetierserver.0 started with pid 17683

**Comment by Baumert7269** [comment]
Hallo zusammen, entschuldigt die wirklich sehr späte Nachricht. Ich schaue mir das Problem mal genau an.

**Comment by Wurzeldoktor** [comment]
Hey danke :) 
Musste gestern wieder auf deinen wechseln, da der coyote Adaoter nen IP Fehler ausspuckt... 

Jetzt ruft dein Adapter die Daten ab, leider fehlt mir nun die Temp abfrage? 
Druckteilabfrage... also die standard sachen vom coyote fehlen mir bei dir... 🤣 evtl hast du ja lust diese zu ergänzen? Oder mir zu sagen wie ich diese Datenpunkte noch bekomme

**Comment by COMHOME** [comment]
Wäre toll, wenn man das Problem in den Griff bekommen könnte! Wir würden die Anbindung gerne produktiv nutzen. Gerne stelle auch ich mich mit Hardware und Zeit aus der Ferne für Tests zur Verfügung.

**Comment by Baumert7269** [comment]
Problem sollte mit der Version 0.0.6 behoben sein.
